version: "3.3"

services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker=true"
      - "--providers.file.filename=/dynamic.yaml"
      - "--providers.file.watch=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--entryPoints.metrics.address=:8082"
      - "--metrics.prometheus.entryPoint=metrics"

    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - traefik-network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./dynamic.yaml:/dynamic.yaml"


  flask_app_post:
    image: "post_api:latest"
    container_name: "post_api"
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      - "traefik.http.routers.flask_app_post.rule=Method(`POST`)"
      - "traefik.http.services.flask_app_post.loadbalancer.server.port=5000"
    environment:
      - "SERVERS=<SERVERS>"

networks:
  traefik-network:
